### ISSUE TITLE
Is there a way to capture output of zk_top.py?

### ISSUE THREAD

**Issue by rootVIII** [phunt/zktop#22]
I guess it's not really an issue... more of a general question. I tried to send output to a file with and without redirection...  Unfortunately I can't get output to a file (a traceback will be output if I redirect stdout - curses.wrapper(ui.show_ui) seems to complain).

 I'm guessing because the script may be redirecting stdout?  Do you have any tips on how to capture the output? Even just a "snapshot" would be great. Thanks.

**Comment by rootVIII** [comment]
Ah nevermind I just printed to a file from within the script... thanks

**Comment by phunt** [comment]
@rootVIII  Having a "snapshot" feature (save current data to disk file) would be cool. If you're interested in adding such a feature please submit a pull request.

**Comment by phunt** [comment]
I never looked at this before but top has a "batch" feature that seems to support this:

https://www.tecmint.com/save-top-command-output-to-a-file/

**Comment by rootVIII** [comment]
Ah okay. Thanks... If I come up with anything I'll let you know. We may be running this as a daemon possibly (for alerting purposes). Thanks again...
