### ISSUE TITLE
non-working with ZK 3.5

### ISSUE THREAD

**Issue by calestyo** [phunt/zktop#28]
Hey.

Today I've upgraded our systems to ZooKeeper 3.5... with that, zktop doesn't seem to work anymore it just shows:
```
Ensemble -- nodecount:0 zxid:0x0 sessions:0

ID SERVER           PORT M    OUTST    RECVD     SENT CONNS MINLAT AVGLAT MAXLA
0  server0  2181 U
1  server1  2181 U
2  server2  2181 U

CLIENT           PORT S I   QUEUED    RECVD     SENT
```
... but ZK itself seems to work fine... any ideas?

Thanks,
Chris

**Comment by phunt** [comment]
Where did you upgrade from? zktop readme says this : https://github.com/phunt/zktop/blob/master/README.textile

_Prereq:

Ensure zoo.cg on all nodes whitelists the minimum [four letter words](https://zookeeper.apache.org/doc/r3.3.3/zookeeperAdmin.html#sc_zkCommands) for zktop to work:

4lw.commands.whitelist=stat,srst_

See this documentation - in 3.5.3 a config was added (security) to disable nearly all 4lw by default - which zktop uses under the covers.

https://zookeeper.apache.org/doc/r3.5.9/zookeeperAdmin.html#sc_zkCommands

If you edit the 4lw.commands.whitelist config parameter, as such, it should work again:

_If you really need enable all four letter word commands by default, you can use the asterisk option so you don't have to include every command one by one in the list. As an example, this will enable all four letter word commands:

4lw.commands.whitelist=*_

Does this resolve the issue for you?

**Comment by calestyo** [comment]
From `3.4.13`. And yes that fixes it for me. Sorry or not having noticed that.

btw: Have you seen that they intend to deprecate these 4 letter words altogether?

> New in 3.5.3: Four Letter Words need to be explicitly white listed before using. Please refer 4lw.commands.whitelist described in cluster configuration section for details. Moving forward, Four Letter Words will be deprecated, please use AdminServer instead.

**Comment by phunt** [comment]
No worries - good to hear it's still working/useful.

Yea, i was part of that (deprecation). :-)   At some point I'll need to move over to the new http base AdminServer....

**Comment by calestyo** [comment]
I quite like it :-)
